apiVersion: v1
kind: Pod
metadata: 
  name: nginx-no-secret
  labels: 
    name: nginx-no-secret
spec: 
  containers:   
  - name: nginx-no-secret
    image: harbor.ilkiformation.fr/project1/nginx:v1
    imagePullPolicy: Always
    resources: 
      limits: 
        memory: "128Mi"
        cpu: "500m"
    ports:       
      - containerPort: 80
